name: Deployment Try

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Create Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      
      - name: Install Packages and Build Application
        run: |
          npm install -g @vue/cli yarn
          yarn install
          npm run build
      
      - name: Set Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Deploy
        run: |
          npx gh-pages -d dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #updated